### ISSUE TITLE
linux: Unable to Dial certain periperals

### ISSUE THREAD

**Issue by deadprogram** [currantlabs/ble#9]
When trying on Ubuntu 14.04 to explore a Parrot Minidrone, I am unable to connect aka `Dial`. I have the same problem with a Sphero Ollie.

Here are my debug logs:

```
$ sudo LOGXI=* ./bin/explorer -name="Mars_143521"
2016/07/02 10:34:56 dev: hci0 up
2016/07/02 10:34:56 dev: hci0 reset
2016/07/02 10:34:56 dev: hci0 down
2016/07/02 10:34:56 dev: hci0 opened
10:34:56.771410 INF hci state +: AdvertisingUpdated
10:34:56.774330 INF hci state -: AdvertisingUpdated
10:34:56.774391 INF hci state +: ScanningUpdated
10:34:56.775491 INF hci state -: ScanningUpdated
10:34:56.775620 INF hci state +: Scanning
10:34:56.777080 INF hci state -: Scanning
10:34:56.899511 INF hci state +: StopScanning
10:34:56.902393 INF hci state -: StopScanning
10:34:56.902439 INF hci state +: StopScanning
10:34:56.902466 INF hci state -: StopScanning
10:34:56.902501 INF hci state +: Dialing
10:34:56.903387 INF hci state -: Dialing
```

The program never connects or times out, it just sits there forever. I have tried using the BLE address instead of the name, but same problem.

The associated HCIDUMP log file is attached.

Thank you!
[mini.txt](https://github.com/currantlabs/ble/files/344462/mini.txt)

**Comment by roylee17** [comment]
```
> HCI Event: LE Meta Event (0x3e) plen 38
    LE Advertising Report
      ADV_IND - Connectable undirected advertising (0)
      bdaddr E0:14:05:A4:3D:A9 (Random)
...
```

```
< HCI Command: LE Create Connection (0x08|0x000d) plen 25
    bdaddr E0:14:05:A4:3D:A9 type 0
```

This is due to the peripheral was advertising "Random" address while we connect it as Public address.
For verify purpose, modify the Connection Parameters in Dial() should be able to connect to them.
```
h.states.connParams.PeerAddressType = 1
```
https://github.com/currantlabs/ble/blob/master/linux/hci/gap.go#L171

Currently, the Dial() API receives Addr, which has only MAC address (on Linux), but no "Address Type".
Either we have to maintain a cache of previously scanned advertisements, or we need a way to pass the address type to Dial() as well. I'll try the latter way and get back soon.

**Comment by deadprogram** [comment]
Hi, @roylee17 

Happy to report that the latest commit allows me to connect to the Parrot Minidrone on Linux. Thank you very much!
